[tool.poetry]
name = "factory-manager"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
django = "2.2"
pytz = "2019.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
